FROM node:14-alpine3.12 as build

# ENV VUE_APP_BACKEND_URL=http://backend-cont:3005

# create destination directory
RUN mkdir -p /app
WORKDIR /app
COPY . /app/

# RUN npm install
RUN npm run build

EXPOSE 3000

FROM nginx:1.21-alpine
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html