version: '3.8'

networks:
  project-network:
    ipam:
      config:
        - subnet: 172.34.0.0/24

services:

 frontend:
  container_name: frontend-cont
  image: frontend-p
  restart: always
  build:
   context: ./frontend
  ports:
   - 3000:80
  # environment:
  #  - VUE_APP_BACKEND_URL=localhost:3005
  # volumes:
  #  - ./:/app
  
  volumes:
   - ./:/app
  networks:
    project-network:
      ipv4_address: 172.34.0.12
      

volumes:
 data:


