version: '3.8'

services:

 mysql:
  container_name: mysql-db
  image: woahbase/alpine-mysql
  restart: always
  ports:
   - 3306:3306
  environment:
   - PGID=100 
   - PUID=1000 
   - MYSQL_ROOT_PWD=insecurebydefault 
   - MYSQL_USER=root 
   - MYSQL_USER_PWD=insecurebydefault 
   - MYSQL_USER_DB=projectdocker 
  volumes:   
   - data:/var/lib/mysql 
      
volumes:
 data:

 